fix:test node

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,16 +23,17 @@ jobs:
           chmod 700 ~/.ssh
 
       - name: ADD SSH known hosts
-        run: ssh-keyscan -H $ {{ secret.EC2_HOST }} >> ~/.ssh/known_hosts
+        run: ssh-keyscan -H $ {{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
 
       - name: test node
-        run: ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+        run: |
+          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
           export NVM_DIR="$HOME/.NVM"
           if [ -s "$NVM_DIR/nvm.sh"]; then
-          ."$NVM_DIR/nvm.sh"
+            ."$NVM_DIR/nvm.sh"
           else
-          echo "nvm.sh not found"
-          exit 1
+            echo "nvm.sh not found"
+            exit 1
           fi
 
           nvm -v'
