test node2

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,4 +25,13 @@ jobs:
         run: ssh-keyscan -H $ {{ sectet.EC2_HOST }} >> ~/.ssh/known_hosts
 
       - name: test node
-        run: ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2)_HOST }} 'node -v'
+        run: ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2)_HOST }} '
+          export NVM_DIR="$HOME/.NVM"
+          if [ -s "$NVM_DIR/nvm.sh"]; then
+          ."$NVM_DIR/nvm.sh"
+          else
+          echo "nvm.sh not found"
+          exit 1
+          fi
+
+          nvm -v'
